apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kimseonguk197/k8s_inflearn.git
    targetRevision: main
    path: manifests/4.ordersystem
  destination:
    server: https://kubernetes.default.svc
    namespace: bradkim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
