apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kimseonguk197/k8s_inflearn.git
    targetRevision: main
    path: 6.argocd/4.ordersystem
  destination:
    server: https://kubernetes.default.svc
    namespace: bradkim
  syncPolicy:
  # Argo CD가 사람이 명령 안 해도 자동으로 GitHub에 있는 매니페스트를 클러스터에 적용
    automated:
    # GitHub에서 삭제된 리소스는 클러스터에서도 자동 삭제
      prune: true
      # 클러스터 안에서 수동으로 리소스가 변경되면, GitHub에 있는 원래 상태로 자동 복구
      selfHeal: true
