apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: bradkim
spec:
  # type: ClusterIP #default는 ClusterIP, NodePort등의 타입을 사용시 service를 통해 외부접근가능
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx
  