apiVersion: apps/v1
kind: Deployment
metadata:
  name: bradkim-msa-member-depl
  namespace: bradkim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bradkim-msa-member
  template:
    metadata:
      labels:
        app: bradkim-msa-member
    spec:
      containers:
      - name: brad-order-backend
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/bradkim-msa-member:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: brad-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: brad-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: brad-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: brad-app-secrets
              key: AWS_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: bradkim-msa-member-service
  namespace: bradkim
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bradkim-msa-member
