# 메트릭 서버 설치
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# 메트릭 서버와 HPA를 통한 pod 현황 조회
# kubectl get hpa brad-order-backend-hpa -n bradkim -w

# 부하 간단 테스트
# while true; do curl -s http://brad-order-backend-service/product/list; done

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: brad-order-backend-hpa
  namespace: bradkim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brad-order-backend
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 50
    scaleDown:
      stabilizationWindowSeconds: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10