apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ironmask431/springboot_on_eks_kubernetes.git # git repo url
    targetRevision: main # target branch
    path: 2.ordersystem/k8s/k8s-ordersystem # ingress, deployment 등 쿠버네티스 자원 yaml 파일이 있는 경로
  destination:
  # https://kubernetes.default.svc: 이는 Argo CD 자체가 설치된 클러스터의 내부 주소
    server: https://kubernetes.default.svc
    namespace: leesh
  syncPolicy:
  # Argo CD가 사람이 명령 안 해도 자동으로 GitHub에 있는 매니페스트를 클러스터에 적용
    automated:
    # GitHub에서 삭제된 리소스는 클러스터에서도 자동 삭제
      prune: true
      # 클러스터 안에서 수동으로 리소스가 변경되면, GitHub에 있는 원래 상태로 자동 복구
      selfHeal: true
